language: cpp
compiler: clang

env:
  - BUILD_ANDROID=1
  - BUILD_HOST=1

script:
  # Compile first, so a compile error fails the build.
  - yes q | sbt compile test:compile scalastyle test:scalastyle checkstyle test:checkstyle
  # Compile again, because sbt coverage deleted our native library.
  - yes q | sbt coverage compile test || true

after_success:
  - yes q | sbt coveralls

before_install:
  - java -version
  - javac -version
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - tools/travis-install "$HOME/travis-cache"

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/travis-cache

# whitelist
branches:
  only:
    - auto

notifications:
  webhooks: http://slevermann.de:54856/travis
