language: scala

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5
      - p7zip-full

cache:
  directories:
    - $HOME/cache

matrix:
  include:
    # Test builds first, since they don't upload things.
    - env: TEST_GOAL=coverage
    - env: TEST_GOAL=coverage
      language: generic
      os: osx
    - env: TEST_GOAL=performance
    # Production builds after test builds so only tested artifacts are uploaded.
    - env: TARGET=x86_64-linux
    - env: TARGET=aarch64-linux-android
    - env: TARGET=arm-linux-androideabi
    - env: TARGET=i686-linux-android
    - env: TARGET=x86_64-linux-android
  fast_finish: true

install:
  # Move files from cache directory.
  - make cache

script:
  - export NDK_HOME=$HOME/android-ndk
  # Setup/build/install/test steps, all together.
  - mkdir -p /tmp/android-travis
  - make all

before_cache:
  - make upload
  # Clean up cache.
  - find $HOME/cache/ivy2 -type f -name "ivydata-*.properties" -delete
  - find $HOME/cache/sbt/boot -name "sbt.*.lock" -delete

branches:
  only:
    - master
